### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by Spigey** [DodoGames7/Dodo-Bot#13]
- add slash commands support and remove the not working slash commands
- add blacklist system
- add music system
- fiinally add the economy system
  - also work command
- fix help menu being displaying commands that don't exist

**Comment by ddodogames** [comment]
1. first of all, economy system exists in beta, work command is also done
2. music system is likely marked as "unPlanned" but there may be an new github branch that can be related to music support
3. slash commands support is fine just the dev that can enable them for now but that is good idea
4. commands that doesn't exist was fixed since 1.7.0-preview
5. about blacklist system, hmm sure that can be useful, there is also `$blackList` function for blacklisting these people, but sure will look into it

**Comment by Spigey** [comment]
then add economy to the main bot :PepeLaugh:

**Comment by ddodogames** [comment]
will do once i release 1.7.0 imo

**Comment by ddodogames** [comment]
Thanks for that suggestion anyways, anything else?

**Comment by Spigey** [comment]
then release 1.7.0 :KEKW:

**Comment by Spigey** [comment]
> Thanks for that suggestion anything else?

fix bugs

**Comment by ddodogames** [comment]
i need to fix the remaining few bugs so i can do that, for status about planned features then you can view this to do [list](https://github.com/users/DodoGames7/projects/3)

**Comment by Spigey** [comment]
> i need to fix the remaining few bugs so i can do that, for status about planned features then you can view this to do [list](https://github.com/users/DodoGames7/projects/3)

Okay

**Comment by ddodogames** [comment]
welp alright, i will leave this for now so i won't locking up this issue, so then anyone can talk about these

**Comment by InikoPro** [comment]
> - add slash commands support and remove the not working slash commands
> - add blacklist system
> - add music system
> - fiinally add the economy system
>   - also work command
> - fix help menu being displaying commands that don't exist

What is blacklist system?

**Comment by ddodogames** [comment]
already explained in my first reply

**Comment by ddodogames** [comment]
wait

**Comment by ddodogames** [comment]
welp i got it wrong, so i will explain, blacklist system is basically an bot ban that can only be used by bot developers, bot developers can use it to ban any rule breaker of their bot from ever using it and if it was an false ban or whatever happened then they can unblacklist the user depending on how they use the bot blacklist system
