### ISSUE TITLE
(Suggestion) Add Avatar Command

### ISSUE THREAD

**Issue by InikoPro** [DodoGames7/Dodo-Bot#14]

**Comment by InikoPro** [comment]
Oh wait, nvm I am wrong, dodo bot have avatar command.

**Comment by ddodogames** [comment]
> Oh wait, nvm I am wrong, dodo bot have avatar command.

actually exists, just use [Github File Finder](https://github.com/DodoGames7/Dodo-Bot/find/v1) next time for searching cmds

**Comment by ddodogames** [comment]
locking this issue for now
