### ISSUE TITLE
daily cooldown is bugged

### ISSUE THREAD

**Issue by Spigey** [DodoGames7/Dodo-Bot#15]
If you use 2 times daily without waiting for one day it just returns
"How about you wait for 0" which I don't think it should return exactly THAT

**Comment by ddodogames** [comment]
noted, thanks for the report, this will be fixed in the next dev build of 1.7.1-dev (or the upcoming beta one here) of the bot

**Comment by ddodogames** [comment]
will close this if fixed, stay tuned

**Comment by ddodogames** [comment]
solved, closing this, thanks for reporting
