### ISSUE TITLE
(off topic)

### ISSUE THREAD

**Issue by InikoPro** [DodoGames7/Dodo-Bot#8]
sorry bro, i am apple for you friend dodo, i was test lol

**Comment by Spigey** [comment]
what about deleting this issue

**Comment by ddodogames** [comment]
lmao it's fine

**Comment by ddodogames** [comment]
i might just close this issue

**Comment by InikoPro** [comment]
can you follow for me in github?

**Comment by Spigey** [comment]
wtf

**Comment by InikoPro** [comment]
?

**Comment by ddodogames** [comment]
> can you follow for me in github?

i already followed you since when you joined, anyway i will consider closing this issue since it counts as "off topic" rather than an actual bug report or support about dodo bot

**Comment by InikoPro** [comment]
> > can you follow for me in github?
> 
> i already followed you since when you joined, anyway i will consider closing this issue since it counts as "off topic" rather than an actual bug report or support about dodo bot

oh ok

**Comment by ddodogames** [comment]
anyway i will lock this conversation
